### ISSUE TITLE
SyntaxError: Non-ASCII character '\xf0' in file ex.py on line 2

### ISSUE THREAD

**Issue by 0D3V** [InMyMine7/SharkXploit#1]
SyntaxError: Non-ASCII character '\xf0' in file ex.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by InMyMine7** [comment]
use python3 sir

> SyntaxError: Non-ASCII character '\xf0' in file ex.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

use python3 sir
